// <auto-generated />
using System;
using System.Collections.Generic;
using BrobyggerPortal.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BrobyggerPortal.Api.Migrations
{
    [DbContext(typeof(BrobyggerDbContext))]
    [Migration("20260813062851_Notifikationer")]
    partial class Notifikationer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BrobyggerPortal.Api.Models.Aftale", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Afdeling")
                        .HasColumnType("text");

                    b.Property<string>("AflysningsAarsag")
                        .HasColumnType("text");

                    b.Property<string>("AflystAf")
                        .HasColumnType("text");

                    b.Property<string>("AftaleForm")
                        .HasColumnType("text");

                    b.Property<string>("Aftaletype")
                        .HasColumnType("text");

                    b.Property<string>("AktivitetsTid")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("BekraeftetAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Beskrivelse")
                        .HasColumnType("text");

                    b.Property<Guid?>("BrobyggerId")
                        .HasColumnType("uuid");

                    b.Property<string>("BrobyggerNote")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("BrobyggerTildeltAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Brobygningstype")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("Dato")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("EfterspurgtAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Finansiering")
                        .HasColumnType("text");

                    b.Property<string>("FremmoedeType")
                        .HasColumnType("text");

                    b.Property<string>("Gentagelse")
                        .HasColumnType("text");

                    b.Property<string>("Henvender")
                        .HasColumnType("text");

                    b.Property<string>("LogNote")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LoggedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MenneskeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Modtager")
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RaadgiverOpfoelgning")
                        .HasColumnType("text");

                    b.Property<string>("Samarbejdspartner")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sted")
                        .HasColumnType("text");

                    b.Property<string>("Transportplan")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Udfald")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Varighed")
                        .HasColumnType("integer");

                    b.Property<int?>("VarighedMin")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BrobyggerId");

                    b.HasIndex("MenneskeId");

                    b.ToTable("Aftaler");
                });

            modelBuilder.Entity("BrobyggerPortal.Api.Models.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Aktoer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Detalje")
                        .HasColumnType("text");

                    b.Property<string>("Handling")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("MaalId")
                        .HasColumnType("uuid");

                    b.Property<string>("MaalType")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Tidspunkt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Tidspunkt");

                    b.ToTable("Auditlog");
                });

            modelBuilder.Entity("BrobyggerPortal.Api.Models.Besked", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Afsender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("AftaleId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Tekst")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Tidspunkt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AftaleId");

                    b.ToTable("Beskeder");
                });

            modelBuilder.Entity("BrobyggerPortal.Api.Models.BeskedSkabelon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("EjerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Indhold")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Skabeloner");
                });

            modelBuilder.Entity("BrobyggerPortal.Api.Models.Brobygger", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Active")
                        .HasColumnType("integer");

                    b.Property<string>("Afdeling")
                        .HasColumnType("text");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<string>("Bio")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Hq")
                        .HasColumnType("text");

                    b.Property<string>("Kon")
                        .HasColumnType("text");

                    b.Property<int>("MaxActive")
                        .HasColumnType("integer");

                    b.Property<string>("NaesteTid")
                        .HasColumnType("text");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Noter")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("SenesteMoede")
                        .HasColumnType("date");

                    b.PrimitiveCollection<List<string>>("Sprog")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateOnly?>("Startdato")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefon")
                        .HasColumnType("text");

                    b.Property<string>("TelefonNorm")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("TilgaengeligFra")
                        .HasColumnType("date");

                    b.PrimitiveCollection<List<string>>("Typer")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TelefonNorm");

                    b.ToTable("Brobyggere");
                });

            modelBuilder.Entity("BrobyggerPortal.Api.Models.Henvendelse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("Dato")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Foerstegang")
                        .HasColumnType("boolean");

                    b.Property<string>("Kanal")
                        .HasColumnType("text");

                    b.Property<Guid>("MenneskeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Resume")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MenneskeId");

                    b.ToTable("Henvendelser");
                });

            modelBuilder.Entity("BrobyggerPortal.Api.Models.Kontaktperson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<Guid>("MenneskeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Noter")
                        .HasColumnType("text");

                    b.Property<string>("Relation")
                        .HasColumnType("text");

                    b.Property<string>("Telefon")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MenneskeId");

                    b.ToTable("Kontaktpersoner");
                });

            modelBuilder.Entity("BrobyggerPortal.Api.Models.Menneske", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Adresse")
                        .HasColumnType("text");

                    b.Property<string>("Afdeling")
                        .HasColumnType("text");

                    b.Property<string>("AfslutAarsag")
                        .HasColumnType("text");

                    b.Property<int?>("AfslutTrivsel")
                        .HasColumnType("integer");

                    b.Property<int?>("Alder")
                        .HasColumnType("integer");

                    b.Property<string>("Brobygningstype")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("HelbredsKategorier")
                        .HasColumnType("text[]");

                    b.Property<byte[]>("HelbredsnoterEnc")
                        .HasColumnType("bytea");

                    b.Property<string>("Hq")
                        .HasColumnType("text");

                    b.Property<string>("Kilde")
                        .HasColumnType("text");

                    b.Property<string>("Kon")
                        .HasColumnType("text");

                    b.Property<Guid?>("MatchedWith")
                        .HasColumnType("uuid");

                    b.Property<string>("Meetpoint")
                        .HasColumnType("text");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Noter")
                        .HasColumnType("text");

                    b.Property<string>("PraeferencerJson")
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("RaadgiverId")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<List<string>>("Sprog")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("SroiMaalgruppe")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefon")
                        .HasColumnType("text");

                    b.Property<string>("TelefonNorm")
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("Typer")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<bool>("UclaFravalgt")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TelefonNorm");

                    b.ToTable("Mennesker");
                });

            modelBuilder.Entity("BrobyggerPortal.Api.Models.Notifikation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Laest")
                        .HasColumnType("boolean");

                    b.Property<string>("Link")
                        .HasColumnType("text");

                    b.Property<string>("Tekst")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Tidspunkt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Tidspunkt");

                    b.ToTable("Notifikationer");
                });

            modelBuilder.Entity("BrobyggerPortal.Api.Models.Opkald", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BrobyggerId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("MenneskeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<string>("Retning")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Tidspunkt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("VarighedSek")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BrobyggerId");

                    b.HasIndex("MenneskeId");

                    b.ToTable("Opkald");
                });

            modelBuilder.Entity("BrobyggerPortal.Api.Models.Stamdata", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Aktiv")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Hovedsaede")
                        .HasColumnType("text");

                    b.Property<string>("Kategori")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Vaerdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Kategori", "Hovedsaede");

                    b.ToTable("Stamdata");
                });

            modelBuilder.Entity("BrobyggerPortal.Api.Models.Trivselsmaaling", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("Dato")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Ensom")
                        .HasColumnType("integer");

                    b.Property<int?>("Faellesskab")
                        .HasColumnType("integer");

                    b.Property<int?>("Hverdag")
                        .HasColumnType("integer");

                    b.Property<string>("Instrument")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("MenneskeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Noter")
                        .HasColumnType("text");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<string>("Slags")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Stoette")
                        .HasColumnType("integer");

                    b.Property<int?>("Velbefindende")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MenneskeId");

                    b.ToTable("Trivselsmaalinger");
                });

            modelBuilder.Entity("BrobyggerPortal.Api.Models.UdlaegKonto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BrobyggerId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Iban")
                        .HasColumnType("text");

                    b.Property<byte[]>("KontoNrEnc")
                        .HasColumnType("bytea");

                    b.Property<string>("RegNr")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BrobyggerId")
                        .IsUnique();

                    b.ToTable("UdlaegKonti");
                });
#pragma warning restore 612, 618
        }
    }
}
