"""
patch_desktop_brobyggere.py
Rewriter DesktopBrobyggere med:
- Fungerende filter-knapper (Alle / Aktive / Pa pause / Nye / Afventer)
- Soegefelt koblet til SS_BROBYGGERE data
- Viser planlagt pause i tabellen
"""
import sys

IN = OUT = 'Brobygger portal.html'
with open(IN, encoding='utf-8') as f:
    html = f.read()

OLD_START = 'const DesktopBrobyggere = () => ('
OLD_END   = 'const DesktopBrobygninger'

if OLD_START not in html or OLD_END not in html:
    sys.exit('ERROR: ankre ikke fundet')

i1 = html.index(OLD_START)
i2 = html.index(OLD_END)

OLD_COMPONENT = html[i1:i2]

NEW_COMPONENT = (
'const DesktopBrobyggere = () => {\n'
'  const [filter, setFilter] = React.useState(\'alle\');\n'
'  const [search,  setSearch]  = React.useState(\'\');\n'
'\n'
'  const TODAY = \'2026-04-26\';\n'
'  const fmtLast = (d) => {\n'
'    if (!d) return \'\u2014\';\n'
'    const days = Math.round((new Date(TODAY) - new Date(d)) / (1000 * 60 * 60 * 24));\n'
'    if (days === 0) return \'i dag\';\n'
'    if (days === 1) return \'i g\u00e5r\';\n'
'    if (days <= 7)  return days + \'d siden\';\n'
'    if (days <= 30) return Math.round(days / 7) + \'u siden\';\n'
'    return Math.round(days / 30) + \'mdr siden\';\n'
'  };\n'
'\n'
'  const FILTERS = [\n'
'    { id: \'alle\',     label: \'Alle\' },\n'
'    { id: \'aktiv\',    label: \'Aktive\' },\n'
'    { id: \'pause\',    label: \'P\u00e5 pause\' },\n'
'    { id: \'ny\',       label: \'Nye\' },\n'
'    { id: \'afventer\', label: \'Afventer\' },\n'
'  ];\n'
'\n'
'  const SS_STYLE = {\n'
'    aktiv:    { bg: SS.sageSoft,       color: SS.sage,      label: \'Aktiv\' },\n'
'    pause:    { bg: SS.sun + \'33\',    color: \'#8A6D1E\',   label: \'Pause\' },\n'
'    ny:       { bg: SS.skySoft,        color: SS.sky,       label: \'Ny\' },\n'
'    afventer: { bg: SS.orange + \'18\', color: SS.orange,    label: \'Afventer\' },\n'
'    afsluttet:{ bg: \'#F0F0F0\',        color: SS.inkMuted,  label: \'Afsluttet\' },\n'
'  };\n'
'\n'
'  const rows = SS_BROBYGGERE\n'
'    .filter(b => filter === \'alle\' || b.status === filter)\n'
'    .filter(b => !search || b.name.toLowerCase().includes(search.toLowerCase()));\n'
'\n'
'  return (\n'
'    <DSCard>\n'
'      {/* Toolbar */}\n'
'      <div style={{ display: \'flex\', gap: 8, marginBottom: 14, flexWrap: \'wrap\' }}>\n'
'        <div style={{ flex: 1, minWidth: 180, display: \'flex\', alignItems: \'center\',\n'
'          gap: 8, background: SS.cream, borderRadius: 8, padding: \'8px 14px\' }}>\n'
'          <Icon name="search" size={14} color={SS.inkMuted}/>\n'
'          <input placeholder={`S\u00f8g i ${SS_BROBYGGERE.length} brobygger...`}\n'
'            value={search} onChange={e => setSearch(e.target.value)}\n'
'            style={{ flex: 1, background: \'transparent\', border: \'none\',\n'
'              outline: \'none\', fontFamily: SS.sans, fontSize: 13 }}/>\n'
'          {search && (\n'
'            <button onClick={() => setSearch(\'\')} style={{ background: \'none\', border: \'none\',\n'
'              cursor: \'pointer\', color: SS.inkMuted, fontSize: 16, lineHeight: 1, padding: 0 }}>x</button>\n'
'          )}\n'
'        </div>\n'
'        <div style={{ display: \'flex\', gap: 6 }}>\n'
'          {FILTERS.map(f => (\n'
'            <button key={f.id} onClick={() => setFilter(f.id)} style={{\n'
'              padding: \'8px 14px\', borderRadius: 8, cursor: \'pointer\',\n'
'              background: filter === f.id ? SS.ink : \'#fff\',\n'
'              color: filter === f.id ? \'#fff\' : SS.ink,\n'
'              border: filter === f.id ? \'none\' : `1px solid ${SS.line}`,\n'
'              fontFamily: SS.sans, fontSize: 12, fontWeight: 600 }}>{f.label}</button>\n'
'          ))}\n'
'        </div>\n'
'      </div>\n'
'\n'
'      {/* Tabel */}\n'
'      <table style={{ width: \'100%\', borderCollapse: \'collapse\' }}>\n'
'        <thead>\n'
'          <tr style={{ borderBottom: `1px solid ${SS.line}` }}>\n'
'            {[\'Navn\', \'Status\', \'Aktive\', \'Denne uge\', \'Sidst aktiv\', \'Planlagt pause\'].map(h => (\n'
'              <th key={h} style={{ textAlign: \'left\', padding: \'10px 8px\',\n'
'                fontFamily: SS.sans, fontSize: 10, fontWeight: 700,\n'
'                color: SS.inkSoft, letterSpacing: 0.8, textTransform: \'uppercase\' }}>{h}</th>\n'
'            ))}\n'
'          </tr>\n'
'        </thead>\n'
'        <tbody>\n'
'          {rows.length === 0 ? (\n'
'            <tr><td colSpan={6} style={{ padding: \'28px 8px\', textAlign: \'center\',\n'
'              fontFamily: SS.sans, fontSize: 13, color: SS.inkMuted }}>\n'
'              Ingen brobyggere matcher filteret\n'
'            </td></tr>\n'
'          ) : rows.map(b => {\n'
'            const ss = SS_STYLE[b.status] || SS_STYLE.aktiv;\n'
'            const hasPause = b.pauseUntil && b.pauseUntil >= TODAY;\n'
'            return (\n'
'              <tr key={b.id} style={{ borderBottom: `1px solid ${SS.lineSoft}`, cursor: \'pointer\' }}\n'
'                onMouseEnter={e => e.currentTarget.style.background = SS.cream}\n'
'                onMouseLeave={e => e.currentTarget.style.background = \'\'}\n'
'              >\n'
'                <td style={{ padding: \'12px 8px\' }}>\n'
'                  <div style={{ display: \'flex\', alignItems: \'center\', gap: 8 }}>\n'
'                    <Avatar initials={b.avatar} bg={b.bg} size={28}/>\n'
'                    <span style={{ fontFamily: SS.sans, fontSize: 13,\n'
'                      fontWeight: 500, color: SS.ink }}>{b.name}</span>\n'
'                  </div>\n'
'                </td>\n'
'                <td style={{ padding: \'12px 8px\' }}>\n'
'                  <Pill bg={ss.bg} color={ss.color}>{ss.label}</Pill>\n'
'                </td>\n'
'                <td style={{ padding: \'12px 8px\', fontFamily: SS.sans,\n'
'                  fontSize: 13, fontWeight: 600, color: SS.ink }}>{b.active}</td>\n'
'                <td style={{ padding: \'12px 8px\', fontFamily: SS.sans,\n'
'                  fontSize: 12, color: SS.inkSoft }}>\n'
'                  {b.thisWeek > 0 ? b.thisWeek + \' afd.\' : \'\u2014\'}\n'
'                </td>\n'
'                <td style={{ padding: \'12px 8px\', fontFamily: SS.sans,\n'
'                  fontSize: 12, color: SS.inkMuted }}>{fmtLast(b.lastActive)}</td>\n'
'                <td style={{ padding: \'12px 8px\' }}>\n'
'                  {hasPause ? (\n'
'                    <Pill bg={SS.sun + \'22\'} color={SS.orangeDeep}>\n'
'                      {b.pauseNote || \'Pause\'}\n'
'                      {\' \u2013 til \'}\n'
'                      {new Date(b.pauseUntil).toLocaleDateString(\'da-DK\', { day: \'numeric\', month: \'short\' })}\n'
'                    </Pill>\n'
'                  ) : (\n'
'                    <span style={{ color: SS.lineSoft, fontFamily: SS.sans, fontSize: 12 }}>\u2014</span>\n'
'                  )}\n'
'                </td>\n'
'              </tr>\n'
'            );\n'
'          })}\n'
'        </tbody>\n'
'      </table>\n'
'\n'
'      {/* Footer */}\n'
'      <div style={{ marginTop: 12, fontFamily: SS.sans, fontSize: 11, color: SS.inkMuted,\n'
'        textAlign: \'right\' }}>\n'
'        {rows.length} af {SS_BROBYGGERE.length} brobyggere\n'
'      </div>\n'
'    </DSCard>\n'
'  );\n'
'};\n'
'\n'
)

html = html[:i1] + NEW_COMPONENT + html[i2:]

with open(OUT, 'w', encoding='utf-8') as f:
    f.write(html)
print(f'[OK] DesktopBrobyggere rewritet med fungerende filtre ({len(html.encode("utf-8")):,} bytes)')
