import sys, re

path = r'C:\Users\Josua Poulsen\Documents\Claude Code\brobygger-portal\Brobygger portal.html'
with open(path, encoding='utf-8') as f:
    html = f.read()
original_len = len(html)

# ── Replace entire DesktopKalender with dense-day–proof version ───────────────
OLD_START = 'const DesktopKalender = () => {'
OLD_END   = '\nconst DesktopRapport = () => ('

idx_start = html.find(OLD_START)
idx_end   = html.find(OLD_END)

if idx_start < 0 or idx_end < 0:
    sys.stdout.buffer.write(b'ERROR: Could not find DesktopKalender boundaries\n')
    sys.exit(1)

NEW_COMPONENT = (
"const DesktopKalender = () => {\n"
"  const [weekOffset, setWeekOffset] = React.useState(0);\n"
"  const [bbFilter,   setBbFilter]   = React.useState('alle');\n"
"  const [view,       setView]       = React.useState('uge');  // 'uge' | 'dag' | 'liste'\n"
"  const [selectedDay, setSelectedDay] = React.useState(null);\n"
"\n"
"  const today = new Date('2026-04-26');\n"
"  const startOfWeek = new Date(today);\n"
"  const dow = today.getDay();\n"
"  startOfWeek.setDate(today.getDate() + (dow === 0 ? -6 : 1 - dow) + weekOffset * 7);\n"
"\n"
"  const days = Array.from({ length: 7 }, (_, i) => {\n"
"    const d = new Date(startOfWeek);\n"
"    d.setDate(startOfWeek.getDate() + i);\n"
"    return d;\n"
"  });\n"
"\n"
"  const mdr      = ['jan','feb','mar','apr','maj','jun','jul','aug','sep','okt','nov','dec'];\n"
"  const dayNames = ['Man','Tir','Ons','Tor','Fre','L\u00f8r','S\u00f8n'];\n"
"  const pad      = n => String(n).padStart(2,'0');\n"
"  const fmtDate  = d => d.getFullYear()+'-'+pad(d.getMonth()+1)+'-'+pad(d.getDate());\n"
"  const weekLabel = days[0].getDate()+'. '+mdr[days[0].getMonth()]\n"
"    +' \u2013 '+days[6].getDate()+'. '+mdr[days[6].getMonth()]+' '+days[6].getFullYear();\n"
"\n"
"  const aktiveBb  = SS_BROBYGGERE.filter(b => ['aktiv','ny'].includes(b.status));\n"
"  const weekDates = new Set(days.map(fmtDate));\n"
"  const weekAppts = SS_APPOINTMENTS_BUSY.filter(a => weekDates.has(a.date));\n"
"  const confirmedCount = weekAppts.filter(a => a.status === 'confirmed').length;\n"
"  const pendingCount   = weekAppts.filter(a => a.status === 'pending').length;\n"
"\n"
"  const getFiltered = dateStr => SS_APPOINTMENTS_BUSY\n"
"    .filter(a => a.date === dateStr && (bbFilter === 'alle' || a.brobyggerId === bbFilter))\n"
"    .sort((a,b) => a.start.localeCompare(b.start));\n"
"\n"
"  const btnBase = { padding:'6px 12px', borderRadius:999, border:'1px solid '+SS.line,\n"
"    fontFamily:SS.sans, fontSize:12, fontWeight:500, cursor:'pointer' };\n"
"\n"
"  // ── Shared appointment card (compact for uge, full for dag/liste) ──────────\n"
"  const ApptCard = ({ a }) => {\n"
"    const m  = SS_MENNESKER[a.menneskeId];\n"
"    const bb = SS_BROBYGGERE.find(b => b.id === a.brobyggerId);\n"
"    const ok = a.status === 'confirmed';\n"
"    return (\n"
"      <div style={{ background:'#fff', borderRadius:10,\n"
"        border:'1px solid '+SS.lineSoft, padding:'12px 14px', marginBottom:8,\n"
"        borderLeft:'4px solid '+(ok ? SS.sage : SS.sun),\n"
"        display:'grid', gridTemplateColumns:'auto 1fr auto', gap:12, alignItems:'center' }}>\n"
"        <div style={{ textAlign:'center', minWidth:38 }}>\n"
"          <div style={{ fontFamily:SS.sans, fontSize:15, fontWeight:700, color:SS.ink }}>{a.start}</div>\n"
"          <div style={{ fontFamily:SS.sans, fontSize:10, color:SS.inkMuted }}>{a.end}</div>\n"
"        </div>\n"
"        <div>\n"
"          <div style={{ fontFamily:SS.sans, fontSize:13, fontWeight:600, color:SS.ink }}>{a.activity}</div>\n"
"          <div style={{ fontFamily:SS.sans, fontSize:12, color:SS.inkSoft, marginTop:2 }}>\n"
"            {m ? m.firstName+' '+m.lastName : '\u2014'}\n"
"          </div>\n"
"          <div style={{ fontFamily:SS.sans, fontSize:11, color:SS.inkMuted, marginTop:1 }}>{a.location}</div>\n"
"        </div>\n"
"        {bb && (\n"
"          <div style={{ textAlign:'center' }}>\n"
"            <div style={{ width:30, height:30, borderRadius:15, background:bb.bg,\n"
"              display:'flex', alignItems:'center', justifyContent:'center', margin:'0 auto 3px',\n"
"              fontFamily:SS.sans, fontSize:11, fontWeight:700, color:'#fff' }}>{bb.avatar}</div>\n"
"            <div style={{ fontFamily:SS.sans, fontSize:9, color:SS.inkMuted }}>{bb.name.split(' ')[0]}</div>\n"
"          </div>\n"
"        )}\n"
"      </div>\n"
"    );\n"
"  };\n"
"\n"
"  // ── Dag view ─────────────────────────────────────────────────────────────\n"
"  const DagView = () => {\n"
"    const ds    = selectedDay || fmtDate(today);\n"
"    const appts = getFiltered(ds);\n"
"    return (\n"
"      <>\n"
"        {/* Day selector strip */}\n"
"        <div style={{ display:'flex', gap:4, marginBottom:14, background:'#fff',\n"
"          borderRadius:12, padding:8, border:'1px solid '+SS.lineSoft, overflowX:'auto' }}>\n"
"          {days.map((d,i) => {\n"
"            const s = fmtDate(d);\n"
"            const sel = s === ds;\n"
"            const cnt = getFiltered(s).length;\n"
"            const ist = s === '2026-04-26';\n"
"            return (\n"
"              <button key={i} onClick={() => setSelectedDay(s)} style={{\n"
"                flex:'0 0 auto', padding:'8px 14px', borderRadius:8, border:'none',\n"
"                background: sel ? SS.orange : 'transparent', cursor:'pointer', textAlign:'center' }}>\n"
"                <div style={{ fontFamily:SS.sans, fontSize:10, fontWeight:700,\n"
"                  color: sel ? '#fff' : SS.inkMuted }}>{dayNames[i]}</div>\n"
"                <div style={{ fontFamily:SS.sans, fontSize:16, fontWeight:700,\n"
"                  color: sel ? '#fff' : (ist ? SS.orange : SS.ink), marginTop:2 }}>{d.getDate()}</div>\n"
"                {cnt > 0 && (\n"
"                  <div style={{ fontFamily:SS.sans, fontSize:10, marginTop:2,\n"
"                    color: sel ? 'rgba(255,255,255,0.75)' : SS.inkMuted }}>{cnt} afd.</div>\n"
"                )}\n"
"              </button>\n"
"            );\n"
"          })}\n"
"        </div>\n"
"        {appts.length === 0\n"
"          ? <div style={{ textAlign:'center', padding:'40px 0',\n"
"              fontFamily:SS.sans, fontSize:14, color:SS.inkMuted }}>Ingen aftaler denne dag</div>\n"
"          : appts.map(a => <ApptCard key={a.id} a={a}/>)\n"
"        }\n"
"      </>\n"
"    );\n"
"  };\n"
"\n"
"  // ── Liste (agenda) view ───────────────────────────────────────────────────\n"
"  const ListeView = () => {\n"
"    const grouped = days\n"
"      .map(d => ({ d, ds: fmtDate(d), appts: getFiltered(fmtDate(d)) }))\n"
"      .filter(g => g.appts.length > 0);\n"
"    if (!grouped.length) return (\n"
"      <div style={{ textAlign:'center', padding:'40px 0',\n"
"        fontFamily:SS.sans, fontSize:14, color:SS.inkMuted }}>Ingen aftaler denne uge</div>\n"
"    );\n"
"    return grouped.map(({ d, ds, appts }, gi) => {\n"
"      const isToday = ds === '2026-04-26';\n"
"      const di = days.findIndex(x => fmtDate(x) === ds);\n"
"      return (\n"
"        <div key={ds} style={{ marginBottom:18 }}>\n"
"          <div style={{ display:'flex', alignItems:'center', gap:10, marginBottom:8 }}>\n"
"            <div style={{ width:38, height:38, borderRadius:19, flexShrink:0,\n"
"              background: isToday ? SS.orange : SS.creamDeep,\n"
"              display:'flex', flexDirection:'column', alignItems:'center', justifyContent:'center' }}>\n"
"              <span style={{ fontFamily:SS.sans, fontSize:8, fontWeight:700,\n"
"                color: isToday ? 'rgba(255,255,255,0.8)' : SS.inkMuted,\n"
"                textTransform:'uppercase' }}>{dayNames[di]}</span>\n"
"              <span style={{ fontFamily:SS.sans, fontSize:14, fontWeight:700, lineHeight:1,\n"
"                color: isToday ? '#fff' : SS.ink }}>{d.getDate()}</span>\n"
"            </div>\n"
"            <div style={{ fontFamily:SS.sans, fontSize:13, fontWeight:600, color:SS.ink }}>\n"
"              {appts.length} {appts.length === 1 ? 'aftale' : 'aftaler'}\n"
"            </div>\n"
"          </div>\n"
"          {appts.map(a => <ApptCard key={a.id} a={a}/>)}\n"
"        </div>\n"
"      );\n"
"    });\n"
"  };\n"
"\n"
"  // ── Uge view ─────────────────────────────────────────────────────────────\n"
"  const MAX_VISIBLE = 3;\n"
"  const UgeView = () => (\n"
"    <div style={{ background:'#fff', borderRadius:12,\n"
"      border:'1px solid '+SS.lineSoft, overflow:'hidden' }}>\n"
"      {/* Day header row — clickable */}\n"
"      <div style={{ display:'grid', gridTemplateColumns:'repeat(7,1fr)',\n"
"        borderBottom:'1px solid '+SS.lineSoft }}>\n"
"        {days.map((day, i) => {\n"
"          const ds = fmtDate(day);\n"
"          const isToday = ds === '2026-04-26';\n"
"          const cnt = getFiltered(ds).length;\n"
"          return (\n"
"            <button key={i} onClick={() => { setSelectedDay(ds); setView('dag'); }} style={{\n"
"              padding:'10px 8px', textAlign:'center', border:'none', cursor:'pointer', width:'100%',\n"
"              borderRight: i<6 ? '1px solid '+SS.lineSoft : 'none',\n"
"              background: isToday ? SS.orange+'0F' : 'transparent' }}>\n"
"              <div style={{ fontFamily:SS.sans, fontSize:10, fontWeight:700,\n"
"                color:SS.inkMuted, letterSpacing:0.6, textTransform:'uppercase' }}>{dayNames[i]}</div>\n"
"              <div style={{\n"
"                width:28, height:28, borderRadius:14,\n"
"                background: isToday ? SS.orange : 'transparent',\n"
"                color: isToday ? '#fff' : SS.ink,\n"
"                display:'flex', alignItems:'center', justifyContent:'center',\n"
"                margin:'4px auto 2px', fontFamily:SS.sans, fontSize:14, fontWeight:600 }}>{day.getDate()}</div>\n"
"              {cnt > 0 && (\n"
"                <div style={{ fontFamily:SS.sans, fontSize:9,\n"
"                  color: isToday ? SS.orange : SS.inkMuted }}>{cnt} afd.</div>\n"
"              )}\n"
"            </button>\n"
"          );\n"
"        })}\n"
"      </div>\n"
"      {/* Appointment slots */}\n"
"      <div style={{ display:'grid', gridTemplateColumns:'repeat(7,1fr)',\n"
"        minHeight:240, alignItems:'start' }}>\n"
"        {days.map((day, i) => {\n"
"          const ds = fmtDate(day);\n"
"          const isToday = ds === '2026-04-26';\n"
"          const all     = getFiltered(ds);\n"
"          const visible  = all.slice(0, MAX_VISIBLE);\n"
"          const overflow = all.length - MAX_VISIBLE;\n"
"          return (\n"
"            <div key={i} style={{\n"
"              padding:'8px 6px', minHeight:120,\n"
"              borderRight: i<6 ? '1px solid '+SS.lineSoft : 'none',\n"
"              background: isToday ? SS.orange+'06' : 'transparent' }}>\n"
"              {all.length === 0 && (\n"
"                <div style={{ textAlign:'center', paddingTop:20,\n"
"                  fontFamily:SS.sans, fontSize:12, color:SS.lineSoft }}>—</div>\n"
"              )}\n"
"              {visible.map(a => {\n"
"                const m  = SS_MENNESKER[a.menneskeId];\n"
"                const bb = SS_BROBYGGERE.find(b => b.id === a.brobyggerId);\n"
"                const ok = a.status === 'confirmed';\n"
"                return (\n"
"                  <div key={a.id} style={{\n"
"                    background: ok ? SS.sageSoft : SS.sun+'33',\n"
"                    borderLeft:'3px solid '+(ok ? SS.sage : SS.sun),\n"
"                    borderRadius:'0 6px 6px 0', padding:'5px 7px', marginBottom:4 }}>\n"
"                    <div style={{ fontFamily:SS.sans, fontSize:10,\n"
"                      fontWeight:700, color:SS.inkSoft }}>{a.start}</div>\n"
"                    <div style={{ fontFamily:SS.sans, fontSize:11,\n"
"                      fontWeight:600, color:SS.ink, lineHeight:1.2 }}>\n"
"                      {m ? m.firstName : '\u2014'}\n"
"                    </div>\n"
"                    <div style={{ fontFamily:SS.sans, fontSize:10,\n"
"                      color:SS.inkSoft, lineHeight:1.2 }}>{a.activity}</div>\n"
"                    {bb && (\n"
"                      <div style={{ display:'flex', alignItems:'center', gap:4, marginTop:3 }}>\n"
"                        <div style={{ width:14, height:14, borderRadius:7, background:bb.bg,\n"
"                          display:'flex', alignItems:'center', justifyContent:'center',\n"
"                          fontFamily:SS.sans, fontSize:7, fontWeight:700,\n"
"                          color:'#fff', flexShrink:0 }}>{bb.avatar[0]}</div>\n"
"                        <div style={{ fontFamily:SS.sans, fontSize:9,\n"
"                          color:SS.inkMuted }}>{bb.name.split(' ')[0]}</div>\n"
"                      </div>\n"
"                    )}\n"
"                  </div>\n"
"                );\n"
"              })}\n"
"              {overflow > 0 && (\n"
"                <button onClick={() => { setSelectedDay(ds); setView('dag'); }} style={{\n"
"                  width:'100%', padding:'5px 4px', borderRadius:6, border:'none',\n"
"                  background:SS.orange+'18', cursor:'pointer',\n"
"                  fontFamily:SS.sans, fontSize:11, fontWeight:700,\n"
"                  color:SS.orangeDeep }}>+{overflow} mere \u2192</button>\n"
"              )}\n"
"            </div>\n"
"          );\n"
"        })}\n"
"      </div>\n"
"    </div>\n"
"  );\n"
"\n"
"  return (\n"
"    <>\n"
"      {/* Top bar: week nav + view toggle */}\n"
"      <div style={{ display:'flex', alignItems:'center', gap:10, marginBottom:14,\n"
"        background:'#fff', borderRadius:12, padding:'12px 16px',\n"
"        border:'1px solid '+SS.lineSoft }}>\n"
"        <button onClick={() => setWeekOffset(w => w-1)}\n"
"          style={{ ...btnBase, background:'transparent', color:SS.inkSoft }}>\u2190</button>\n"
"        <div style={{ flex:1, textAlign:'center', fontFamily:SS.sans,\n"
"          fontSize:14, fontWeight:600, color:SS.ink }}>{weekLabel}</div>\n"
"        <button onClick={() => setWeekOffset(0)} style={{ ...btnBase,\n"
"          background: weekOffset===0 ? SS.orange : 'transparent',\n"
"          color: weekOffset===0 ? '#fff' : SS.inkSoft,\n"
"          borderColor: weekOffset===0 ? SS.orange : SS.line }}>I dag</button>\n"
"        <button onClick={() => setWeekOffset(w => w+1)}\n"
"          style={{ ...btnBase, background:'transparent', color:SS.inkSoft }}>\u2192</button>\n"
"        <div style={{ display:'flex', background:SS.creamDeep, borderRadius:8, padding:3, gap:2 }}>\n"
"          {[['uge','Uge'],['dag','Dag'],['liste','Liste']].map(([k,l]) => (\n"
"            <button key={k} onClick={() => setView(k)} style={{\n"
"              padding:'5px 10px', borderRadius:6, border:'none', cursor:'pointer',\n"
"              fontFamily:SS.sans, fontSize:12, fontWeight:600,\n"
"              background: view===k ? '#fff' : 'transparent',\n"
"              color: view===k ? SS.ink : SS.inkMuted,\n"
"              boxShadow: view===k ? '0 1px 3px rgba(0,0,0,0.08)' : 'none' }}>{l}</button>\n"
"          ))}\n"
"        </div>\n"
"      </div>\n"
"\n"
"      {/* Stats */}\n"
"      <div style={{ display:'grid', gridTemplateColumns:'repeat(3,1fr)', gap:10, marginBottom:14 }}>\n"
"        {[\n"
"          { l:'Aftaler denne uge', v:weekAppts.length, c:SS.ink },\n"
"          { l:'Bekr\u00e6ftede',       v:confirmedCount,   c:SS.sage },\n"
"          { l:'Afventer',           v:pendingCount,     c:SS.sun },\n"
"        ].map((s,i) => (\n"
"          <div key={i} style={{ background:'#fff', borderRadius:10,\n"
"            border:'1px solid '+SS.lineSoft, padding:'12px 14px' }}>\n"
"            <div style={{ fontFamily:SS.sans, fontSize:10, fontWeight:700,\n"
"              color:SS.inkMuted, letterSpacing:0.8, textTransform:'uppercase',\n"
"              marginBottom:4 }}>{s.l}</div>\n"
"            <div style={{ fontFamily:SS.font, fontSize:28, fontWeight:500, color:s.c }}>{s.v}</div>\n"
"          </div>\n"
"        ))}\n"
"      </div>\n"
"\n"
"      {/* Brobygger filter */}\n"
"      <div style={{ display:'flex', gap:6, marginBottom:12, flexWrap:'wrap' }}>\n"
"        <button onClick={() => setBbFilter('alle')} style={{ ...btnBase,\n"
"          background: bbFilter==='alle' ? SS.ink : 'transparent',\n"
"          color: bbFilter==='alle' ? '#fff' : SS.inkSoft,\n"
"          borderColor: bbFilter==='alle' ? SS.ink : SS.line }}>Alle</button>\n"
"        {aktiveBb.map(b => (\n"
"          <button key={b.id} onClick={() => setBbFilter(b.id)} style={{ ...btnBase,\n"
"            background: bbFilter===b.id ? b.bg : 'transparent',\n"
"            color: bbFilter===b.id ? '#fff' : SS.inkSoft,\n"
"            borderColor: bbFilter===b.id ? b.bg : SS.line }}>{b.name.split(' ')[0]}</button>\n"
"        ))}\n"
"      </div>\n"
"\n"
"      {/* Active view */}\n"
"      {view === 'uge'   && <UgeView/>}\n"
"      {view === 'dag'   && <DagView/>}\n"
"      {view === 'liste' && <ListeView/>}\n"
"    </>\n"
"  );\n"
"};\n"
)

html = html[:idx_start] + NEW_COMPONENT + html[idx_end:]

# ── Verify div balance ────────────────────────────────────────────────────────
import re as _re
new_idx   = html.find('const DesktopKalender = () => {')
new_end   = html.find('\nconst DesktopRapport = () => (')
chunk     = html[new_idx:new_end]
opens     = len(_re.findall(r'<div[\s{>]', chunk))
closes    = len(_re.findall(r'</div>', chunk))
self_c    = len(_re.findall(r'<div[^>]*/>', chunk))
effective = opens - self_c
balanced  = effective == closes

sys.stdout.buffer.write(
    f"DesktopKalender: opens={opens}, self={self_c}, effective={effective}, closes={closes} "
    f"{'OK' if balanced else 'MISMATCH'}\n"
    f"File: {original_len:,} -> {len(html):,} bytes\n".encode('utf-8')
)

if balanced:
    with open(path, 'w', encoding='utf-8') as f:
        f.write(html)
    sys.stdout.buffer.write(b"Saved.\n")
else:
    sys.stdout.buffer.write(b"NOT saved - div mismatch.\n")
