path = r'C:\Users\Josua Poulsen\Documents\Claude Code\Brobygger portal.html'
with open(path, encoding='utf-8') as f:
    html = f.read()

# ── A. Fix QuickLink navigation ───────────────────────────────────────────────
old_ql = """                <QuickLink icon="users" label="Brobyggere" count={brobyggere.length}/>
                <QuickLink icon="heart" label="Mennesker" count={Object.keys(SS_BORGERE).length}/>
                <QuickLink icon="calendar" label="Kalender" count="Uge 17"/>
                <QuickLink icon="bell" label="Beskeder" count="2 nye"
                  onClick={() => setTab('beskeder')}/>"""

new_ql = """                <QuickLink icon="users" label="Brobyggere" count={brobyggere.length}
                  onClick={() => setTab('brobyggere')}/>
                <QuickLink icon="heart" label="Mennesker" count={Object.keys(SS_BORGERE).length}
                  onClick={() => setTab('mennesker')}/>
                <QuickLink icon="calendar" label="Kalender" count="Uge 17"
                  onClick={() => setTab('overview')}/>
                <QuickLink icon="bell" label="Beskeder" count="2 nye"
                  onClick={() => setTab('beskeder')}/>"""

if old_ql in html:
    html = html.replace(old_ql, new_ql, 1)
    print("Fixed QuickLink navigation")
else:
    print("ERROR: QuickLink block not found")
    # debug
    idx = html.find('QuickLink icon="users"')
    print(repr(html[idx-10:idx+120]))

# ── B. Replace AdminSettings with expanded version ────────────────────────────
start_marker = 'const AdminSettings = '
end_marker = '\nwindow.AdminMobile = AdminMobile;'

start_idx = html.find(start_marker)
end_idx   = html.find(end_marker, start_idx)

if start_idx < 0 or end_idx < 0:
    print(f"ERROR: AdminSettings block not found ({start_idx}, {end_idx})")
else:
    old_block = html[start_idx:end_idx]

    new_block = (
        "const AdminSettings = ({ currentHq, ownHq, onPick, onClose, isAdmin }) => {\n"
        "  const [section, setSection] = React.useState(null);\n"
        "  const [picked, setPicked] = React.useState(currentHq);\n"
        "  const [dataAccess, setDataAccess] = React.useState({ daysBefore: 7, daysAfter: 7 });\n"
        "  const [lifecycle, setLifecycle] = React.useState({ warningMonths: 2, pauseMonths: 4, endMonths: 8 });\n"
        "  const [staff, setStaff] = React.useState(SS_MEDARBEJDERE.filter(u => u.hq === ownHq));\n"
        "  const [saved, setSaved] = React.useState(false);\n"
        "  const [bbInvite, setBbInvite] = React.useState({ name: '', email: '', phone: '' });\n"
        "  const [bbSent, setBbSent] = React.useState(false);\n"
        "  const [staffInvite, setStaffInvite] = React.useState({ name: '', email: '', role: 'raadgiver' });\n"
        "  const [staffSent, setStaffSent] = React.useState(false);\n"
        "\n"
        "  const TODAY = new Date('2026-04-24');\n"
        "  const monthsSince = (d) => (TODAY - new Date(d)) / (1000 * 60 * 60 * 24 * 30.4);\n"
        "  const bbAlert = (b) => {\n"
        "    const m = monthsSince(b.lastActive);\n"
        "    if (m >= lifecycle.endMonths)     return { label: 'Afsluttes snart',  color: SS.rose };\n"
        "    if (m >= lifecycle.pauseMonths)   return { label: 'Foresl\u00e5s pause',   color: SS.sun };\n"
        "    if (m >= lifecycle.warningMonths) return { label: 'Inaktiv',          color: SS.sun };\n"
        "    return null;\n"
        "  };\n"
        "  const atRisk = SS_BROBYGGERE.filter(b => bbAlert(b));\n"
        "  const saveAndBack = () => { setSaved(true); setTimeout(() => { setSaved(false); setSection(null); }, 1200); };\n"
        "\n"
        "  const NumStepper = ({ label, sublabel, unit, value, min, max, onChange }) => (\n"
        "    <div style={{ display: 'flex', alignItems: 'center', gap: 12,\n"
        "      padding: '13px 0', borderBottom: `1px solid ${SS.lineSoft}` }}>\n"
        "      <div style={{ flex: 1 }}>\n"
        "        <div style={{ fontFamily: SS.sans, fontSize: 14, fontWeight: 500, color: SS.ink }}>{label}</div>\n"
        "        {sublabel && <div style={{ fontFamily: SS.sans, fontSize: 11, color: SS.inkMuted, marginTop: 2 }}>{sublabel}</div>}\n"
        "      </div>\n"
        "      <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>\n"
        "        <button onClick={() => onChange(Math.max(min, value - 1))} style={{\n"
        "          width: 30, height: 30, borderRadius: 15, border: `1.5px solid ${SS.lineSoft}`,\n"
        "          background: '#fff', cursor: 'pointer', fontSize: 18, color: SS.ink,\n"
        "          display: 'flex', alignItems: 'center', justifyContent: 'center',\n"
        "        }}>\u2212</button>\n"
        "        <div style={{ textAlign: 'center', minWidth: 38 }}>\n"
        "          <div style={{ fontFamily: SS.font, fontSize: 20, fontWeight: 500, color: SS.orange }}>{value}</div>\n"
        "          {unit && <div style={{ fontFamily: SS.sans, fontSize: 9, color: SS.inkMuted }}>{unit}</div>}\n"
        "        </div>\n"
        "        <button onClick={() => onChange(Math.min(max, value + 1))} style={{\n"
        "          width: 30, height: 30, borderRadius: 15, border: `1.5px solid ${SS.lineSoft}`,\n"
        "          background: '#fff', cursor: 'pointer', fontSize: 18, color: SS.ink,\n"
        "          display: 'flex', alignItems: 'center', justifyContent: 'center',\n"
        "        }}>+</button>\n"
        "      </div>\n"
        "    </div>\n"
        "  );\n"
        "\n"
        "  const Field = ({ label, placeholder, value, onChange, required }) => (\n"
        "    <div style={{ marginBottom: 12 }}>\n"
        "      <div style={{ fontFamily: SS.sans, fontSize: 11, fontWeight: 600,\n"
        "        color: SS.inkSoft, marginBottom: 5 }}>\n"
        "        {label}{required && <span style={{ color: SS.orange }}> *</span>}\n"
        "      </div>\n"
        "      <input placeholder={placeholder} value={value} onChange={e => onChange(e.target.value)}\n"
        "        style={{ width: '100%', padding: '11px 13px', fontFamily: SS.sans,\n"
        "          fontSize: 14, color: SS.ink, background: '#fff',\n"
        "          border: `1.5px solid ${SS.lineSoft}`, borderRadius: SS.r.md,\n"
        "          outline: 'none', boxSizing: 'border-box' }} />\n"
        "    </div>\n"
        "  );\n"
        "\n"
        "  const SECTIONS = [\n"
        "    { id: 'hq',        icon: 'building', label: 'Hoveds\u00e6de',         sub: `Viser ${currentHq}`, show: true },\n"
        "    { id: 'data',      icon: 'lock',     label: 'Databeskyttelse',        sub: `F\u00f8lsomt data: \u00b1${dataAccess.daysBefore}/${dataAccess.daysAfter} dage`, show: true },\n"
        "    { id: 'lifecycle', icon: 'calendar', label: 'Brobygger-livscyklus',   sub: `Afslutning efter ${lifecycle.endMonths} m\u00e5neder`, show: true },\n"
        "    { id: 'staff',     icon: 'users',    label: 'Medarbejdere & roller',  sub: `${staff.length} p\u00e5 ${ownHq}`, show: isAdmin },\n"
        "    { id: 'invite-bb', icon: 'user',     label: 'Inviter brobygger',      sub: 'Send invitationslink', show: true },\n"
        "  ];\n"
        "  const TITLES = {\n"
        "    hq: 'Hoveds\u00e6de', data: 'Databeskyttelse', lifecycle: 'Brobygger-livscyklus',\n"
        "    staff: 'Medarbejdere & roller', 'invite-bb': 'Inviter brobygger',\n"
        "  };\n"
        "\n"
        "  return (\n"
        "    <div style={{ position: 'absolute', inset: 0, background: SS.cream, display: 'flex', flexDirection: 'column' }}>\n"
        "      {/* Header */}\n"
        "      <div style={{ padding: '54px 20px 16px', background: '#fff',\n"
        "        borderBottom: `1px solid ${SS.lineSoft}`,\n"
        "        display: 'flex', alignItems: 'center', gap: 12, flexShrink: 0 }}>\n"
        "        <button onClick={section ? () => setSection(null) : onClose}\n"
        "          style={{ background: 'none', border: 'none', padding: 4, cursor: 'pointer' }}>\n"
        "          <Icon name=\"chevronL\" size={22} color={SS.ink}/>\n"
        "        </button>\n"
        "        <div>\n"
        "          <div style={{ fontFamily: SS.font, fontSize: 22, fontWeight: 500 }}>\n"
        "            {section ? TITLES[section] : 'Indstillinger'}\n"
        "          </div>\n"
        "          {!section && <div style={{ fontFamily: SS.sans, fontSize: 12, color: SS.inkSoft }}>\n"
        "            {ownHq} \u00b7 {isAdmin ? 'Admin' : 'R\u00e5dgiver'}\n"
        "          </div>}\n"
        "        </div>\n"
        "      </div>\n"
        "\n"
        "      {/* Body */}\n"
        "      <div style={{ flex: 1, overflowY: 'auto', padding: 20 }}>\n"
        "\n"
        "        {/* MENU */}\n"
        "        {!section && (<>\n"
        "          {SECTIONS.filter(s => s.show).map(s => (\n"
        "            <button key={s.id} onClick={() => setSection(s.id)} style={{\n"
        "              display: 'flex', alignItems: 'center', gap: 14, width: '100%',\n"
        "              padding: '14px 16px', marginBottom: 8, textAlign: 'left',\n"
        "              background: '#fff', border: `1px solid ${SS.lineSoft}`,\n"
        "              borderRadius: SS.r.md, cursor: 'pointer',\n"
        "            }}>\n"
        "              <div style={{ width: 40, height: 40, borderRadius: 20, background: SS.creamDeep,\n"
        "                flexShrink: 0, display: 'flex', alignItems: 'center', justifyContent: 'center' }}>\n"
        "                <Icon name={s.icon} size={18} color={SS.inkSoft}/>\n"
        "              </div>\n"
        "              <div style={{ flex: 1 }}>\n"
        "                <div style={{ fontFamily: SS.sans, fontSize: 14, fontWeight: 600, color: SS.ink }}>{s.label}</div>\n"
        "                <div style={{ fontFamily: SS.sans, fontSize: 12, color: SS.inkSoft, marginTop: 2 }}>{s.sub}</div>\n"
        "              </div>\n"
        "              <Icon name=\"chevronR\" size={16} color={SS.inkMuted}/>\n"
        "            </button>\n"
        "          ))}\n"
        "          {atRisk.length > 0 && (\n"
        "            <div onClick={() => setSection('lifecycle')}\n"
        "              style={{ marginTop: 8, padding: '12px 14px', background: SS.sun + '22',\n"
        "                border: `1px solid ${SS.sun}`, borderRadius: SS.r.md, cursor: 'pointer' }}>\n"
        "              <div style={{ fontFamily: SS.sans, fontSize: 12, fontWeight: 700, color: SS.orangeDeep }}>\n"
        "                {atRisk.length} brobygger{atRisk.length > 1 ? 'e' : ''} kr\u00e6ver opm\u00e6rksomhed\n"
        "              </div>\n"
        "              <div style={{ fontFamily: SS.sans, fontSize: 11, color: SS.inkSoft, marginTop: 3 }}>\n"
        "                {atRisk.map(b => b.name.split(' ')[0]).join(', ')} \u2014 tjek livscyklus \u2192\n"
        "              </div>\n"
        "            </div>\n"
        "          )}\n"
        "        </>)}\n"
        "\n"
        "        {/* HQ */}\n"
        "        {section === 'hq' && (<>\n"
        "          <SectionHead title=\"Dit hoveds\u00e6de\"/>\n"
        "          <div style={{ background: '#fff', borderRadius: SS.r.md, padding: 16,\n"
        "            border: `1px solid ${SS.lineSoft}`, marginBottom: 20,\n"
        "            display: 'flex', alignItems: 'center', gap: 12 }}>\n"
        "            <div style={{ width: 12, height: 12, borderRadius: 6, background: SS.hq[ownHq] || SS.orange }}/>\n"
        "            <div style={{ flex: 1 }}>\n"
        "              <div style={{ fontFamily: SS.sans, fontSize: 14, fontWeight: 600, color: SS.ink }}>{ownHq}</div>\n"
        "              <div style={{ fontFamily: SS.sans, fontSize: 11, color: SS.inkSoft }}>Dit prim\u00e6re hoveds\u00e6de</div>\n"
        "            </div>\n"
        "            <Pill bg={SS.sageSoft} color={SS.sage}>Standard</Pill>\n"
        "          </div>\n"
        "          <SectionHead title=\"Midlertidigt skift\"/>\n"
        "          <div style={{ padding: 12, background: SS.creamDeep, borderRadius: SS.r.md,\n"
        "            marginBottom: 12, display: 'flex', gap: 10 }}>\n"
        "            <Icon name=\"lock\" size={16} color={SS.orangeDeep}/>\n"
        "            <div style={{ fontFamily: SS.sans, fontSize: 11, color: SS.orangeDeep, lineHeight: 1.5 }}>\n"
        "              Nulstilles ved logout. Handlinger logges i revisionsspor.\n"
        "            </div>\n"
        "          </div>\n"
        "          {SS_HOVEDSAEDER.filter(h => h !== ownHq).map(h => {\n"
        "            const sel = picked === h;\n"
        "            return (\n"
        "              <button key={h} onClick={() => setPicked(h)} style={{\n"
        "                display: 'flex', alignItems: 'center', gap: 12, width: '100%',\n"
        "                padding: 14, marginBottom: 6, textAlign: 'left', background: '#fff',\n"
        "                border: `2px solid ${sel ? (SS.hq[h] || SS.orange) : SS.lineSoft}`,\n"
        "                borderRadius: SS.r.md, cursor: 'pointer',\n"
        "              }}>\n"
        "                <div style={{ width: 12, height: 12, borderRadius: 6, background: SS.hq[h] || SS.orange }}/>\n"
        "                <span style={{ flex: 1, fontFamily: SS.sans, fontSize: 14, color: SS.ink }}>{h}</span>\n"
        "                {sel && <Icon name=\"check\" size={16} color={SS.hq[h] || SS.orange}/>}\n"
        "              </button>\n"
        "            );\n"
        "          })}\n"
        "          <button onClick={() => onPick(picked)} style={{\n"
        "            width: '100%', marginTop: 12, padding: '14px 0',\n"
        "            background: picked !== currentHq ? SS.orange : SS.lineSoft,\n"
        "            color: picked !== currentHq ? '#fff' : SS.inkMuted,\n"
        "            border: 'none', borderRadius: SS.r.md,\n"
        "            fontFamily: SS.sans, fontSize: 15, fontWeight: 600, cursor: 'pointer',\n"
        "          }}>Skift til {picked}</button>\n"
        "        </>)}\n"
        "\n"
        "        {/* DATABESKYTTELSE */}\n"
        "        {section === 'data' && (<>\n"
        "          <div style={{ background: '#FFF8F0', border: `1.5px solid ${SS.orange}30`,\n"
        "            borderRadius: SS.r.md, padding: '12px 14px', marginBottom: 20 }}>\n"
        "            <div style={{ fontFamily: SS.sans, fontSize: 12, fontWeight: 700,\n"
        "              color: SS.orange, marginBottom: 4 }}>GDPR \u2014 Artikel 9 (f\u00f8lsomme oplysninger)</div>\n"
        "            <div style={{ fontFamily: SS.sans, fontSize: 12, color: SS.inkSoft, lineHeight: 1.5 }}>\n"
        "              Brobyggere m\u00e5 kun se diagnoser og helbredsoplysninger i en periode rundt om\n"
        "              aktive brobygninger. Udenfor vinduet vises kun brobygningstype og behov.\n"
        "            </div>\n"
        "          </div>\n"
        "          <div style={{ background: '#fff', borderRadius: SS.r.md,\n"
        "            border: `1px solid ${SS.lineSoft}`, padding: '0 16px', marginBottom: 20 }}>\n"
        "            <NumStepper label=\"Dage f\u00f8r aftalen\" unit=\"dage\"\n"
        "              sublabel=\"Brobygger f\u00e5r adgang X dage inden brobygningen\"\n"
        "              value={dataAccess.daysBefore} min={1} max={30}\n"
        "              onChange={v => setDataAccess(d => ({ ...d, daysBefore: v }))}/>\n"
        "            <NumStepper label=\"Dage efter aftalen\" unit=\"dage\"\n"
        "              sublabel=\"Adgang forts\u00e6tter X dage efter seneste brobygning\"\n"
        "              value={dataAccess.daysAfter} min={1} max={30}\n"
        "              onChange={v => setDataAccess(d => ({ ...d, daysAfter: v }))}/>\n"
        "          </div>\n"
        "          <div style={{ background: SS.creamDeep, borderRadius: SS.r.md,\n"
        "            padding: '12px 14px', marginBottom: 20 }}>\n"
        "            <div style={{ fontFamily: SS.sans, fontSize: 12, fontWeight: 600, color: SS.ink, marginBottom: 4 }}>\n"
        "              Eksempel med nuv\u00e6rende indstillinger\n"
        "            </div>\n"
        "            {(() => {\n"
        "              const appt = new Date('2026-05-01');\n"
        "              const bef = new Date(appt); bef.setDate(bef.getDate() - dataAccess.daysBefore);\n"
        "              const aft = new Date(appt); aft.setDate(aft.getDate() + dataAccess.daysAfter);\n"
        "              const fmt = d => d.toLocaleDateString('da-DK', { day: 'numeric', month: 'long' });\n"
        "              return <div style={{ fontFamily: SS.sans, fontSize: 12, color: SS.inkSoft, lineHeight: 1.6 }}>\n"
        "                Aftale d. 1. maj \u2192 adgang fra <strong>{fmt(bef)}</strong> til <strong>{fmt(aft)}</strong>\n"
        "              </div>;\n"
        "            })()}\n"
        "          </div>\n"
        "          <button onClick={saveAndBack} style={{\n"
        "            width: '100%', padding: '14px 0',\n"
        "            background: saved ? SS.sage : SS.orange, color: '#fff',\n"
        "            border: 'none', borderRadius: SS.r.md,\n"
        "            fontFamily: SS.sans, fontSize: 15, fontWeight: 600, cursor: 'pointer',\n"
        "          }}>{saved ? '\u2713 Gemt' : 'Gem indstillinger'}</button>\n"
        "        </>)}\n"
        "\n"
        "        {/* LIVSCYKLUS */}\n"
        "        {section === 'lifecycle' && (<>\n"
        "          <div style={{ fontFamily: SS.sans, fontSize: 13, color: SS.inkSoft,\n"
        "            marginBottom: 16, lineHeight: 1.5 }}>\n"
        "            Det er sv\u00e6rt at vide, hvorn\u00e5r en brobygger ikke vil mere. Disse parametre\n"
        "            s\u00e6tter automatiske reaktioner p\u00e5 inaktivitet, s\u00e5 ingen tabes stille.\n"
        "          </div>\n"
        "          <div style={{ background: '#fff', borderRadius: SS.r.md,\n"
        "            border: `1px solid ${SS.lineSoft}`, padding: '0 16px', marginBottom: 20 }}>\n"
        "            <NumStepper label=\"Varsling til r\u00e5dgiver\" unit=\"m\u00e5n.\"\n"
        "              sublabel=\"M\u00e5neder uden brobygning \u2192 notifikation til r\u00e5dgiver\"\n"
        "              value={lifecycle.warningMonths} min={1} max={12}\n"
        "              onChange={v => setLifecycle(l => ({ ...l, warningMonths: v }))}/>\n"
        "            <NumStepper label=\"Automatisk pause\" unit=\"m\u00e5n.\"\n"
        "              sublabel=\"M\u00e5neder uden brobygning \u2192 status s\u00e6ttes til 'pause'\"\n"
        "              value={lifecycle.pauseMonths} min={1} max={24}\n"
        "              onChange={v => setLifecycle(l => ({ ...l, pauseMonths: v }))}/>\n"
        "            <NumStepper label=\"Automatisk afslutning\" unit=\"m\u00e5n.\"\n"
        "              sublabel=\"M\u00e5neder uden aktivitet \u2192 brobygger afsluttes automatisk\"\n"
        "              value={lifecycle.endMonths} min={1} max={36}\n"
        "              onChange={v => setLifecycle(l => ({ ...l, endMonths: v }))}/>\n"
        "          </div>\n"
        "          {atRisk.length > 0 && (<>\n"
        "            <SectionHead title=\"Kr\u00e6ver opm\u00e6rksomhed nu\"/>\n"
        "            {atRisk.map(b => {\n"
        "              const st = bbAlert(b);\n"
        "              const m = monthsSince(b.lastActive);\n"
        "              return (\n"
        "                <div key={b.id} style={{ display: 'flex', alignItems: 'center', gap: 12,\n"
        "                  padding: 14, background: '#fff', marginBottom: 8,\n"
        "                  borderRadius: SS.r.md, border: `1.5px solid ${st.color}50` }}>\n"
        "                  <div style={{ width: 36, height: 36, borderRadius: 18, background: b.bg,\n"
        "                    display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 }}>\n"
        "                    <span style={{ fontFamily: SS.sans, fontSize: 11, fontWeight: 700, color: '#fff' }}>{b.avatar}</span>\n"
        "                  </div>\n"
        "                  <div style={{ flex: 1, minWidth: 0 }}>\n"
        "                    <div style={{ fontFamily: SS.sans, fontSize: 13, fontWeight: 600, color: SS.ink }}>{b.name}</div>\n"
        "                    <div style={{ fontFamily: SS.sans, fontSize: 11, color: SS.inkSoft, marginTop: 2 }}>\n"
        "                      Inaktiv {Math.round(m * 10) / 10} m\u00e5neder\n"
        "                      {` \u00b7 sidst aktiv ${new Date(b.lastActive).toLocaleDateString('da-DK', { day: 'numeric', month: 'short' })}`}\n"
        "                    </div>\n"
        "                  </div>\n"
        "                  <Pill bg={st.color + '22'} color={st.color}>{st.label}</Pill>\n"
        "                </div>\n"
        "              );\n"
        "            })}\n"
        "          </>)}\n"
        "          <div style={{ background: SS.creamDeep, borderRadius: SS.r.md,\n"
        "            padding: '12px 14px', marginBottom: 20 }}>\n"
        "            <div style={{ fontFamily: SS.sans, fontSize: 12, fontWeight: 600, color: SS.ink, marginBottom: 4 }}>\n"
        "              Om automatisk afslutning\n"
        "            </div>\n"
        "            <div style={{ fontFamily: SS.sans, fontSize: 12, color: SS.inkSoft, lineHeight: 1.5 }}>\n"
        "              N\u00e5r en brobygger afsluttes automatisk, sendes en venlig e-mail der takker\n"
        "              for indsatsen og inviterer dem til at vende tilbage n\u00e5r de har tid.\n"
        "              Aktive brobygningsforl\u00f8b overf\u00f8res til r\u00e5dgiveren inden afslutning.\n"
        "            </div>\n"
        "          </div>\n"
        "          <button onClick={saveAndBack} style={{\n"
        "            width: '100%', padding: '14px 0',\n"
        "            background: saved ? SS.sage : SS.orange, color: '#fff',\n"
        "            border: 'none', borderRadius: SS.r.md,\n"
        "            fontFamily: SS.sans, fontSize: 15, fontWeight: 600, cursor: 'pointer',\n"
        "          }}>{saved ? '\u2713 Gemt' : 'Gem parametre'}</button>\n"
        "        </>)}\n"
        "\n"
        "        {/* MEDARBEJDERE */}\n"
        "        {section === 'staff' && (<>\n"
        "          <div style={{ fontFamily: SS.sans, fontSize: 13, color: SS.inkSoft,\n"
        "            marginBottom: 16, lineHeight: 1.5 }}>\n"
        "            Tildel roller til medarbejdere p\u00e5 {ownHq}. Kun admins kan \u00e6ndre roller.\n"
        "          </div>\n"
        "          {staff.map(u => (\n"
        "            <div key={u.id} style={{ display: 'flex', alignItems: 'center', gap: 12,\n"
        "              padding: 14, background: '#fff', marginBottom: 8,\n"
        "              borderRadius: SS.r.md, border: `1px solid ${SS.lineSoft}` }}>\n"
        "              <div style={{ width: 40, height: 40, borderRadius: 20, background: u.bg,\n"
        "                display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 }}>\n"
        "                <span style={{ fontFamily: SS.sans, fontSize: 13, fontWeight: 700, color: '#fff' }}>{u.avatar}</span>\n"
        "              </div>\n"
        "              <div style={{ flex: 1, minWidth: 0 }}>\n"
        "                <div style={{ fontFamily: SS.sans, fontSize: 14, fontWeight: 600, color: SS.ink }}>{u.name}</div>\n"
        "                <div style={{ fontFamily: SS.sans, fontSize: 11, color: SS.inkSoft, marginTop: 1,\n"
        "                  overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{u.email}</div>\n"
        "              </div>\n"
        "              {isAdmin ? (\n"
        "                <select value={u.role}\n"
        "                  onChange={e => setStaff(s => s.map(m => m.id === u.id ? { ...m, role: e.target.value } : m))}\n"
        "                  style={{ fontFamily: SS.sans, fontSize: 12, fontWeight: 600,\n"
        "                    color: u.role === 'admin' ? SS.orange : SS.sage,\n"
        "                    background: u.role === 'admin' ? SS.orange + '15' : SS.sageSoft,\n"
        "                    border: 'none', borderRadius: 999, padding: '5px 10px', cursor: 'pointer' }}>\n"
        "                  <option value=\"raadgiver\">R\u00e5dgiver</option>\n"
        "                  <option value=\"admin\">Admin</option>\n"
        "                </select>\n"
        "              ) : (\n"
        "                <Pill bg={u.role === 'admin' ? SS.orange + '15' : SS.sageSoft}\n"
        "                  color={u.role === 'admin' ? SS.orange : SS.sage}>\n"
        "                  {u.role === 'admin' ? 'Admin' : 'R\u00e5dgiver'}\n"
        "                </Pill>\n"
        "              )}\n"
        "            </div>\n"
        "          ))}\n"
        "          <div style={{ marginTop: 20 }}>\n"
        "            <SectionHead title=\"Inviter medarbejder\"/>\n"
        "            {staffSent ? (\n"
        "              <div style={{ padding: 16, background: SS.sageSoft, borderRadius: SS.r.md,\n"
        "                fontFamily: SS.sans, fontSize: 14, color: SS.sage, textAlign: 'center' }}>\n"
        "                \u2713 Invitation sendt til {staffInvite.email}\n"
        "              </div>\n"
        "            ) : (<>\n"
        "              <Field label=\"Navn\" placeholder=\"Fulde navn\" required\n"
        "                value={staffInvite.name} onChange={v => setStaffInvite(si => ({ ...si, name: v }))}/>\n"
        "              <Field label=\"E-mail\" placeholder=\"navn@socialsundhed.dk\"\n"
        "                value={staffInvite.email} onChange={v => setStaffInvite(si => ({ ...si, email: v }))}/>\n"
        "              <div style={{ marginBottom: 14 }}>\n"
        "                <div style={{ fontFamily: SS.sans, fontSize: 11, fontWeight: 600,\n"
        "                  color: SS.inkSoft, marginBottom: 5 }}>Rolle</div>\n"
        "                <div style={{ display: 'flex', gap: 8 }}>\n"
        "                  {['raadgiver', 'admin'].map(r => (\n"
        "                    <button key={r} onClick={() => setStaffInvite(si => ({ ...si, role: r }))} style={{\n"
        "                      flex: 1, padding: '10px 0', fontFamily: SS.sans, fontSize: 13, fontWeight: 600,\n"
        "                      color: staffInvite.role === r ? '#fff' : SS.inkSoft,\n"
        "                      background: staffInvite.role === r ? SS.orange : '#fff',\n"
        "                      border: `1.5px solid ${staffInvite.role === r ? SS.orange : SS.lineSoft}`,\n"
        "                      borderRadius: SS.r.md, cursor: 'pointer',\n"
        "                    }}>{r === 'raadgiver' ? 'R\u00e5dgiver' : 'Admin'}</button>\n"
        "                  ))}\n"
        "                </div>\n"
        "              </div>\n"
        "              <button disabled={!staffInvite.name || !staffInvite.email}\n"
        "                onClick={() => setStaffSent(true)} style={{\n"
        "                  width: '100%', padding: '13px 0',\n"
        "                  background: staffInvite.name && staffInvite.email ? SS.orange : SS.lineSoft,\n"
        "                  color: staffInvite.name && staffInvite.email ? '#fff' : SS.inkMuted,\n"
        "                  border: 'none', borderRadius: SS.r.md,\n"
        "                  fontFamily: SS.sans, fontSize: 14, fontWeight: 600, cursor: 'pointer',\n"
        "                }}>Send invitation</button>\n"
        "            </>)}\n"
        "          </div>\n"
        "        </>)}\n"
        "\n"
        "        {/* INVITER BROBYGGER */}\n"
        "        {section === 'invite-bb' && (<>\n"
        "          <div style={{ fontFamily: SS.sans, fontSize: 13, color: SS.inkSoft,\n"
        "            marginBottom: 20, lineHeight: 1.5 }}>\n"
        "            Send en invitationslink til en potentiel brobygger. De opretter selv en profil\n"
        "            og g\u00e5r igennem onboarding, inden du godkender dem.\n"
        "          </div>\n"
        "          {bbSent ? (\n"
        "            <div style={{ padding: 20, background: SS.sageSoft, borderRadius: SS.r.md, textAlign: 'center' }}>\n"
        "              <div style={{ fontFamily: SS.font, fontSize: 22, fontWeight: 500,\n"
        "                color: SS.sage, marginBottom: 6 }}>Invitation sendt \u2713</div>\n"
        "              <div style={{ fontFamily: SS.sans, fontSize: 13, color: SS.inkSoft }}>\n"
        "                {bbInvite.name} f\u00e5r en e-mail eller SMS med link. Invitationen udl\u00f8ber efter 14 dage.\n"
        "              </div>\n"
        "              <button onClick={() => { setBbSent(false); setBbInvite({ name: '', email: '', phone: '' }); }}\n"
        "                style={{ marginTop: 16, padding: '10px 20px', background: 'transparent',\n"
        "                  border: `1px solid ${SS.lineSoft}`, borderRadius: SS.r.md,\n"
        "                  fontFamily: SS.sans, fontSize: 13, cursor: 'pointer', color: SS.inkSoft }}>\n"
        "                Inviter endnu en\n"
        "              </button>\n"
        "            </div>\n"
        "          ) : (<>\n"
        "            <Field label=\"Navn\" placeholder=\"F\u00f8r- og efternavn\" required\n"
        "              value={bbInvite.name} onChange={v => setBbInvite(b => ({ ...b, name: v }))}/>\n"
        "            <Field label=\"E-mail\" placeholder=\"Valgfrit\"\n"
        "              value={bbInvite.email} onChange={v => setBbInvite(b => ({ ...b, email: v }))}/>\n"
        "            <Field label=\"Telefon\" placeholder=\"Valgfrit \u2014 til SMS-invitation\"\n"
        "              value={bbInvite.phone} onChange={v => setBbInvite(b => ({ ...b, phone: v }))}/>\n"
        "            <div style={{ background: SS.creamDeep, borderRadius: SS.r.md,\n"
        "              padding: '10px 14px', marginBottom: 16 }}>\n"
        "              <div style={{ fontFamily: SS.sans, fontSize: 11, color: SS.inkSoft, lineHeight: 1.5 }}>\n"
        "                Den nye brobygger g\u00e5r selv igennem onboarding og vises som\n"
        "                \u201dafventer godkendelse\u201d indtil du godkender dem. Invitation udl\u00f8ber efter 14 dage.\n"
        "              </div>\n"
        "            </div>\n"
        "            <button disabled={!bbInvite.name} onClick={() => setBbSent(true)} style={{\n"
        "              width: '100%', padding: '14px 0',\n"
        "              background: bbInvite.name ? SS.orange : SS.lineSoft,\n"
        "              color: bbInvite.name ? '#fff' : SS.inkMuted,\n"
        "              border: 'none', borderRadius: SS.r.md,\n"
        "              fontFamily: SS.sans, fontSize: 15, fontWeight: 600, cursor: 'pointer',\n"
        "            }}>Send invitation</button>\n"
        "          </>)}\n"
        "        </>)}\n"
        "      </div>\n"
        "    </div>\n"
        "  );\n"
        "};"
    )

    html = html.replace(old_block, new_block, 1)
    print("Replaced AdminSettings with expanded version")

# ── C. Add SS_MEDARBEJDERE mock data (before SS_USER) ────────────────────────
old_ss_user = "const SS_USER = {"
new_medarbejdere = """const SS_MEDARBEJDERE = [
  { id: 'u1', name: 'Mette Kj\u00e6rsgaard', avatar: 'MK', bg: '#E87A3E', role: 'admin',     hq: 'Aarhus', email: 'mette@socialsundhed.dk', joined: '2023-02-01' },
  { id: 'u2', name: 'Peter Lund',        avatar: 'PL', bg: '#6B8CAE', role: 'raadgiver', hq: 'Aarhus', email: 'peter@socialsundhed.dk', joined: '2024-01-10' },
  { id: 'u3', name: 'Dina Osman',        avatar: 'DO', bg: '#7FA089', role: 'raadgiver', hq: 'Aarhus', email: 'dina@socialsundhed.dk',  joined: '2024-06-15' },
  { id: 'u4', name: 'Rasmus Holm',       avatar: 'RH', bg: '#8C6BAE', role: 'raadgiver', hq: 'Midt',   email: 'rasmus@socialsundhed.dk',joined: '2025-03-01' },
];

const SS_USER = {"""

if old_ss_user in html and 'SS_MEDARBEJDERE' not in html:
    html = html.replace(old_ss_user, new_medarbejdere, 1)
    print("Added SS_MEDARBEJDERE mock data")
elif 'SS_MEDARBEJDERE' in html:
    print("SS_MEDARBEJDERE already present — skipping")
else:
    print("ERROR: SS_USER not found for medarbejdere insertion")

# ── D. Add lastActive to SS_BROBYGGERE if not present ────────────────────────
if 'lastActive' not in html:
    old_bb_short = "{ id: 'bb-1', name: 'Maja Holmberg'"
    if old_bb_short in html:
        # It's the old format without lastActive — shouldn't happen, but handle gracefully
        print("WARNING: SS_BROBYGGERE missing lastActive — manual patch needed")
    else:
        print("SS_BROBYGGERE lastActive already present or not found")
else:
    print("SS_BROBYGGERE already has lastActive — OK")

# ── E. Pass isAdmin to AdminSettings ─────────────────────────────────────────
old_settings_call = '      content = <AdminSettings\n        currentHq={viewingHq}\n        ownHq="Aarhus"\n        onPick={(hq) => { setViewingHq(hq); setSettingsOpen(false); }}\n        onClose={() => setSettingsOpen(false)} />;'
new_settings_call = '      content = <AdminSettings\n        currentHq={viewingHq}\n        ownHq="Aarhus"\n        isAdmin={tweaks.role === "admin"}\n        onPick={(hq) => { setViewingHq(hq); setSettingsOpen(false); }}\n        onClose={() => setSettingsOpen(false)} />;'

if old_settings_call in html:
    html = html.replace(old_settings_call, new_settings_call, 1)
    print("Passed isAdmin to AdminSettings")
elif 'isAdmin={tweaks.role === "admin"}' in html and 'onPick={(hq)' in html:
    print("isAdmin already passed to AdminSettings — OK")
else:
    print("WARNING: AdminSettings call pattern not matched exactly")

with open(path, 'w', encoding='utf-8') as f:
    f.write(html)

print(f"\nDone. File: {len(html):,} bytes")
